yaml_content = """
name: adaboost_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.5
  - numpy=2.0.1
  - pandas=2.2.2
  - matplotlib=3.9.1
  - scikit-learn=1.5.1
"""

yaml_path = '/mnt/data/environment.yaml'

# Save the YAML file
with open(yaml_path, 'w') as yaml_file:
    yaml_file.write(yaml_content)

yaml_path
